/**
 * Agent Installation Script
 * Installs the worker as a system service using PM2
 */
import * as fs from 'fs';
import * as path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';
import * as dotenv from 'dotenv';

// Load environment variables from .env file
dotenv.config();

const execAsync = promisify(exec);

interface AgentConfig {
  agentId: string;
  name: string;
  location?: string;
  countryCode?: string;
  country?: string;
  city?: string;
  ip?: string;
  asn?: string;
}

async function installAgent() {
  console.log('🚀 Installing Check-Host Worker Agent...\n');

  try {
    // Check if PM2 is installed
    try {
      await execAsync('pm2 --version');
    } catch {
      console.log('📦 Installing PM2...');
      await execAsync('npm install -g pm2');
    }

    // Read agent configuration from environment
    // AGENT_ID should be set in .env file (auto-generated by deployment system)
    const agentId = process.env.AGENT_ID;
    if (!agentId) {
      console.error('❌ Error: AGENT_ID is required but not set in .env file');
      console.error('   Please ensure AGENT_ID is set in your .env file');
      process.exit(1);
    }

    const config: AgentConfig = {
      agentId: agentId,
      name: process.env.AGENT_NAME || 'Check-Host Worker Agent',
      location: process.env.AGENT_LOCATION,
      countryCode: process.env.AGENT_COUNTRY_CODE,
      country: process.env.AGENT_COUNTRY,
      city: process.env.AGENT_CITY,
      ip: process.env.AGENT_IP,
      asn: process.env.AGENT_ASN
    };

    // Build the project (skip if already built in deployment process)
    // Check if dist folder exists and has recent files
    const distPath = path.join(process.cwd(), 'dist');
    const indexJsPath = path.join(distPath, 'index.js');
    let needsBuild = true;
    
    if (fs.existsSync(distPath) && fs.existsSync(indexJsPath)) {
      try {
        const distStat = fs.statSync(distPath);
        const indexStat = fs.statSync(indexJsPath);
        // Build if older than 1 minute
        const oneMinuteAgo = Date.now() - 60000;
        needsBuild = distStat.mtime.getTime() < oneMinuteAgo || indexStat.mtime.getTime() < oneMinuteAgo;
      } catch (error) {
        // If stat fails, assume we need to build
        needsBuild = true;
      }
    }
    
    if (needsBuild) {
      console.log('🔨 Building project...');
      await execAsync('npm run build');
    } else {
      console.log('✅ Project already built, skipping build step');
    }

    // Create PM2 ecosystem file
    const ecosystemConfig = {
      apps: [{
        name: 'check-host-worker',
        script: './dist/index.js',
        instances: 1,
        exec_mode: 'fork',
        env: {
          NODE_ENV: 'production',
          ...process.env
        },
        error_file: './logs/error.log',
        out_file: './logs/out.log',
        log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
        merge_logs: true,
        autorestart: true,
        max_memory_restart: '1G'
      }]
    };

    const ecosystemPath = path.join(process.cwd(), 'ecosystem.config.js');
    fs.writeFileSync(
      ecosystemPath,
      `module.exports = ${JSON.stringify(ecosystemConfig, null, 2)};`
    );

    // Create logs directory
    const logsDir = path.join(process.cwd(), 'logs');
    if (!fs.existsSync(logsDir)) {
      fs.mkdirSync(logsDir, { recursive: true });
    }

    // Check if PM2 process is already running
    let isRunning = false;
    try {
      const pm2ListOutput = await execAsync('pm2 list --no-color');
      isRunning = pm2ListOutput.stdout.includes('check-host-worker') && 
                  (pm2ListOutput.stdout.includes('online') || pm2ListOutput.stdout.includes('│ online'));
    } catch (error) {
      // PM2 list failed, assume not running
    }

    if (isRunning) {
      // Process is already running, restart it
      console.log('🔄 Restarting agent with PM2...');
      await execAsync('pm2 restart check-host-worker');
    } else {
      // Start with PM2
      console.log('🚀 Starting agent with PM2...');
      await execAsync(`pm2 start ${ecosystemPath}`);
    }
    
    // Setup PM2 startup script (must be done before pm2 save)
    console.log('⚙️  Setting up PM2 startup script...');
    let startupConfigured = false;
    
    try {
      const startupOutput = await execAsync('pm2 startup');
      console.log(startupOutput.stdout);
      
      // Extract the sudo command from pm2 startup output
      // PM2 startup output typically contains a line like:
      // "sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u username --hp /home/username"
      const outputLines = startupOutput.stdout.split('\n');
      let startupCommand: string | null = null;
      
      for (const line of outputLines) {
        // Look for lines that start with "sudo" and contain "pm2 startup"
        const trimmedLine = line.trim();
        if (trimmedLine.startsWith('sudo') && trimmedLine.includes('pm2 startup')) {
          startupCommand = trimmedLine;
          break;
        }
      }
      
      if (startupCommand) {
        console.log(`🔧 Executing startup command: ${startupCommand}`);
        try {
          // Execute the startup command
          const startupResult = await execAsync(startupCommand);
          console.log(startupResult.stdout);
          if (startupResult.stderr && startupResult.stderr.trim()) {
            console.log(startupResult.stderr);
          }
          console.log('✅ PM2 startup script configured successfully');
          startupConfigured = true;
        } catch (startupError: any) {
          // If sudo command fails, try alternative method
          console.warn('⚠️  Could not execute PM2 startup command with sudo.');
          console.warn(`   Error: ${startupError.message}`);
          
          // Try alternative: get user info and construct command directly
          try {
            const userInfo = await execAsync('whoami');
            const homeInfo = await execAsync('echo $HOME');
            const username = userInfo.stdout.trim();
            const homeDir = homeInfo.stdout.trim();
            const nodePath = await execAsync('which node');
            const nodeDir = nodePath.stdout.trim().replace('/bin/node', '');
            const pm2Path = await execAsync('which pm2');
            const pm2Dir = pm2Path.stdout.trim().replace('/bin/pm2', '');
            
            // Try to detect init system
            let initSystem = 'systemd';
            try {
              await execAsync('which systemctl');
              // systemctl exists, use systemd
              initSystem = 'systemd';
            } catch {
              // systemctl not found, try other init systems
              try {
                await execAsync('ls /etc/init.d/pm2-init.sh');
                initSystem = 'upstart';
              } catch {
                // Default to systemd
                initSystem = 'systemd';
              }
            }
            
            const altCommand = `sudo env PATH=$PATH:${nodeDir}/bin:${pm2Dir}/bin pm2 startup ${initSystem} -u ${username} --hp ${homeDir}`;
            console.log(`🔄 Trying alternative method: ${altCommand}`);
            
            try {
              const altResult = await execAsync(altCommand);
              console.log(altResult.stdout);
              if (altResult.stderr && altResult.stderr.trim()) {
                console.log(altResult.stderr);
              }
              console.log('✅ PM2 startup script configured successfully (alternative method)');
              startupConfigured = true;
            } catch (altError: any) {
              console.warn('⚠️  Alternative method also failed.');
              console.warn(`   Error: ${altError.message}`);
              console.warn('   Please run the command manually with sudo privileges:');
              console.warn(`   ${startupCommand}\n`);
            }
          } catch (infoError: any) {
            console.warn('⚠️  Could not get system information for alternative method.');
            console.warn('   Please run the command manually with sudo privileges:');
            console.warn(`   ${startupCommand}\n`);
          }
        }
      } else {
        // Check if PM2 startup is already configured
        try {
          // Check if startup script already exists
          const checkStartup = await execAsync('pm2 startup 2>&1');
          if (checkStartup.stdout.includes('already') || 
              checkStartup.stdout.includes('exists') ||
              checkStartup.stdout.includes('already configured')) {
            console.log('✅ PM2 startup script is already configured');
            startupConfigured = true;
          } else {
            console.warn('⚠️  Could not extract startup command from PM2 output.');
            console.warn('   Please run "pm2 startup" manually and execute the provided command.');
          }
        } catch {
          // Ignore errors in checking
        }
      }
    } catch (startupError: any) {
      console.warn('⚠️  Warning: Could not setup PM2 startup script.');
      console.warn(`   Error: ${startupError.message}`);
      console.warn('   Please run "pm2 startup" manually and execute the provided command.\n');
    }
    
    if (!startupConfigured) {
      console.warn('⚠️  PM2 startup script was not configured automatically.');
      console.warn('   The agent will NOT start automatically after server restart.');
      console.warn('   Please configure it manually by running: pm2 startup\n');
    }
    
    // Save PM2 configuration (must be done after pm2 startup)
    console.log('💾 Saving PM2 configuration...');
    await execAsync('pm2 save');
    console.log('✅ PM2 configuration saved');

    console.log('✅ Agent installed successfully!');
    console.log('\nUseful commands:');
    console.log('  pm2 status          - Check agent status');
    console.log('  pm2 logs            - View logs');
    console.log('  pm2 restart check-host-worker - Restart agent');
    console.log('  pm2 stop check-host-worker    - Stop agent');
    console.log('  pm2 delete check-host-worker  - Remove agent\n');

  } catch (error: any) {
    console.error('❌ Error installing agent:', error.message);
    process.exit(1);
  }
}

// Run installation
if (require.main === module) {
  installAgent();
}

export { installAgent };

